### ISSUE TITLE
Someone missed to call pair method 

### ISSUE THREAD

**Issue by abupskill** [jetbrains-academy/scala-tutorial#52]
Someone missed to call pair method from the first line of main method due to which the suggested change in pair method never gets executed. 

![scala-tutorial-bug](https://user-images.githubusercontent.com/61430200/161930021-641f5c74-6f21-4d7f-b03c-5e350d42b4bd.png)

**Comment by sofiiako** [comment]
@abupskill Thanks a lot! The issue was fixed
