### ISSUE TITLE
DefinitionsAndEvaluation [bug]

### ISSUE THREAD

**Issue by KryPat** [jetbrains-academy/scala-tutorial#58]
There is an error with line 1 expression.

Still appears after reset.

ss of the problem:
![DnitionsAndEvaluations ERR](https://user-images.githubusercontent.com/105121795/181352928-555b039d-d467-4f0c-a0b2-3237b11b8c2a.png)

**Comment by sofiiako** [comment]
Hi @Woodierini! Thank you for your feedback!
It appears that placeholders were broken in this task at some point. Fixed it in version 11 of the course
