### ISSUE TITLE
Definitions and Evaluation / Naming Things2

### ISSUE THREAD

**Issue by KryPat** [jetbrains-academy/scala-tutorial#59]
While import scala.math task is marked as incorrect, while the result is correct

Without importing the module, task marks as correct

EDIT:
Its the Math.PI causing error

ss off the issue:
![DefinitionsAndEvaluations2 ERR](https://user-images.githubusercontent.com/105121795/181359806-c205e5be-ca8e-44fd-8abc-151135270032.png)
![DefinitionsAndEvaluations2 ERR2](https://user-images.githubusercontent.com/105121795/181364025-6f4646fd-ede4-49d8-aa05-f2afa5e43b29.png)

**Comment by sofiiako** [comment]
Hi! updated tests to handle both solutions (with math.pi and with 3.14159)
https://github.com/jetbrains-academy/scala-tutorial/pull/61/commits/ca94579974fad3493f299c40f8f942b069d206b6
